conf: add commercial to LICENSE_FLAGS_WHITELIST
this addresses the below problem:
ERROR: Nothing RPROVIDES 'gstreamer1.0-libav' (but
poky/meta-qti-bsp/recipes-core/packagegroups/packagegroup-multimedia.bb
RDEPENDS on or otherwise requires it)
ERROR: gstreamer1.0-libav was skipped: because it has a restricted license
not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'gstreamer1.0-libav' is unbuildable, removing...

Change-Id: If47a1dc151c3a09884cb060d14cfc97b6cb0ea4e
Signed-off-by: Barry Song <baohuas@codeaurora.org>